language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
branches:
  only:
    - development
    - master
scripts:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then audit-ci --moderate; fi
  - npm test
