language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
branches:
  only:
    - development
    - master
before_script:
  - npm install audit-ci eslint
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run audit-ci --moderate; fi
  - npm run lint
  - npm test
