language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
branches:
  only:
    - development
    - master
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run audit-ci --moderate; fi
  - npm lint
  - npm test
