language: node_js
branches:
  - development
  - master
node_js:
  - '8'
  - '10'
  - '11'
  - '12'

cache:
  directories:
    - $HOME/.npm

before_script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm install audit-ci && npm run audit-ci --moderate; fi
  - npm install eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser codecov
script:
  - npm run lint
  - npm test
  - codecov -f coverage/*.json
