language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
branches:
  only:
    - development
    - master
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm i -g audit-ci && audit-ci -m; fi
